
apiVersion: v1
kind: Pod
metadata:
  name: download-artifacts-pod
  labels:
    app: download-artifacts
spec:
  restartPolicy: Never
  containers:
  - name: ods-ci-test-results
    command:
    - /bin/bash
    - -c
    - 'trap : TERM INT; sleep 100'
    image: docker.io/openshift/origin-cli
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - mountPath: /tmp/artifacts
      name: artifacts
  serviceAccount: manifests-test-sa
  serviceAccountName: manifests-test-sa
  volumes:
  - name: artifacts
    persistentVolumeClaim:
      claimName: ods-ci
  
