kind: StarburstEnterprise
apiVersion: charts.starburstdata.com/v1alpha1
metadata:
  name: starburstenterprise-sample
  namespace: starburst-operator
spec:
  additionalVolumes: []
  cache:
    diskUsagePercentage: 80
    enabled: false
    ttl: 7d
    volume:
      emptyDir: {}
  catalogs:
    tpch: |-
      connector.name=tpch
      tpch.splits-per-node=4
  commonLabels: {}
  coordinator:
    additionalProperties: ''
    affinity: {}
    deploymentAnnotations: {}
    envFrom: []
    etcFiles:
      jvm.config: |
        -server
        -XX:-UseBiasedLocking
        -XX:+UseG1GC
        -XX:G1HeapRegionSize=32M
        -XX:+ExplicitGCInvokesConcurrent
        -XX:+ExitOnOutOfMemoryError
        -XX:+HeapDumpOnOutOfMemoryError
        -XX:-OmitStackTraceInFastThrow
        -XX:ReservedCodeCacheSize=512M
        -XX:PerMethodRecompilationCutoff=10000
        -XX:PerBytecodeRecompilationCutoff=10000
        -Djdk.nio.maxCachedBufferSize=2000000
        -Djdk.attach.allowAttachSelf=true
      other: {}
      properties:
        config.properties: |
          coordinator=true
          node-scheduler.include-coordinator=false
          http-server.http.port=8080
          discovery.uri=http://localhost:8080
          discovery-server.enabled=true
        log.properties: |
          # Enable verbose logging from Starburst Enterprise
          #io.trino=DEBUG
          #com.starburstdata.presto=DEBUG
        node.properties: |
          node.environment={{ include "starburst.environment" . }}
          node.data-dir=/data/starburst
          plugin.dir=/usr/lib/starburst/plugin
          node.server-log-file=/var/log/starburst/server.log
          node.launcher-log-file=/var/log/starburst/launcher.log
    heapHeadroomPercentage: 30
    heapSizePercentage: 90
    nodeMemoryHeadroom: 2Gi
    nodeSelector: {}
    podAnnotations: {}
    priorityClassName: null
    resources:
      limits:
        cpu: 2
      memory: 4Gi
      requests:
        cpu: 2
    tolerations: []
  environment: null
  expose:
    clusterIp:
      name: starburst
      ports:
        http:
          port: 8080
    ingress:
      annotations: {}
      host: null
      ingressClassName: null
      ingressName: coordinator-ingress
      path: /
      serviceName: starburst
      servicePort: 8080
      tls:
        enabled: true
        secretName: null
    loadBalancer:
      IP: ''
      annotations: {}
      name: starburst
      ports:
        http:
          port: 8080
      sourceRanges: []
    nodePort:
      extraLabels: {}
      name: starburst
      ports:
        http:
          nodePort: 30080
          port: 8080
    type: clusterIp
  externalSecrets:
    enabled: false
    goDaddy:
      backendType: secretsManager
    secretPrefix: external0
    type: goDaddy
  extraArguments: []
  extraSecret:
    file: null
    name: null
  image:
    pullPolicy: IfNotPresent
    repository: registry.connect.redhat.com/starburst/starburst-enterprise
    tag: 360-e.6-ubi
  imagePullSecrets: null
  initFile: ''
  initImage:
    pullPolicy: IfNotPresent
    repository: registry.connect.redhat.com/starburst/starburst-enterprise-init
    tag: 360.6.1-ubi
  internal:
    ports:
      http:
        port: 8080
      https:
        port: 8443
  internalTls: false
  livenessProbe: null
  prometheus:
    agent:
      config: /etc/starburst/telemetry/prometheus.yaml
      port: 8081
      version: 0.15.0
    enabled: true
    rules:
      - attrNameSnakeCase: true
        name: $1
        pattern: trino.execution<name=QueryManager><>(running_queries|queued_queries)
        type: GAUGE
      - name: failed_queries
        pattern: trino.execution<name=QueryManager><>FailedQueries\.TotalCount
        type: COUNTER
  query:
    maxConcurrentQueries: 3
  readinessProbe: null
  registryCredentials:
    enabled: false
    password: null
    registry: registry.connect.redhat.com
    username: null
  securityContext: {}
  sharedSecret: null
  spilling:
    enabled: false
    volume:
      emptyDir: {}
  starburst-charts-common:
    global: {}
  usageMetrics:
    enabled: true
    reporter:
      configFiles:
        config.json: ''
      enabled: false
      image:
        pullPolicy: IfNotPresent
        repository: harbor.starburstdata.net/testing/usage-metrics-reporter
        tag: 0.1.3-alpha
    usageClient:
      initialDelay: 1m
      interval: 1m
  userDatabase:
    enabled: false
    users:
      - password: 46991b33f7a75ff79213c0dc0e610610
        username: admin
  worker:
    additionalProperties: ''
    affinity: {}
    autoscaling:
      enabled: false
      maxReplicas: 100
      minReplicas: 1
      targetCPUUtilizationPercentage: 80
    deploymentAnnotations: {}
    deploymentTerminationGracePeriodSeconds: 300
    envFrom: []
    etcFiles:
      jvm.config: |
        -server
        -XX:-UseBiasedLocking
        -XX:+UseG1GC
        -XX:G1HeapRegionSize=32M
        -XX:+ExplicitGCInvokesConcurrent
        -XX:+ExitOnOutOfMemoryError
        -XX:+HeapDumpOnOutOfMemoryError
        -XX:-OmitStackTraceInFastThrow
        -XX:ReservedCodeCacheSize=512M
        -XX:PerMethodRecompilationCutoff=10000
        -XX:PerBytecodeRecompilationCutoff=10000
        -Djdk.nio.maxCachedBufferSize=2000000
        -Djdk.attach.allowAttachSelf=true
      other: {}
      properties:
        config.properties: |
          coordinator=false
          http-server.http.port=8080
          discovery.uri=http://coordinator:8080
        log.properties: |
          # Enable verbose logging from Starburst Enterprise
          #io.trino=DEBUG
          #com.starburstdata.presto=DEBUG
        node.properties: |
          node.environment={{ include "starburst.environment" . }}
          node.data-dir=/data/starburst
          plugin.dir=/usr/lib/starburst/plugin
          node.server-log-file=/var/log/starburst/server.log
          node.launcher-log-file=/var/log/starburst/launcher.log
    heapHeadroomPercentage: 30
    heapSizePercentage: 90
    nodeMemoryHeadroom: 2Gi
    nodeSelector: {}
    podAnnotations: {}
    priorityClassName: null
    replicas: 2
    resources:
      limits:
        cpu: 2
      memory: 4Gi
      requests:
        cpu: 2
    starburstWorkerShutdownGracePeriodSeconds: 120
    tolerations: []

